Create operation
PI2-Estacao-de-Recarga/ESDR-User-control pull request #7
Opened 2023-01-28 19:33 UTC by AlineLermen

2023-01-29 14:52 UTC, lucasA27 requested changes

2023-01-29 14:52 UTC, lucasA27 commented on src/usecases/create-operation/use-case.ts
> +      if (payload.operationType == OperationTypeEnum.USO && payload.creditAmount > user.balance) {
adicionar === para também comparar o tipo de dado

2023-01-29 14:52 UTC, lucasA27 commented on src/usecases/create-operation/use-case.ts
> +      if (payload.operationType == OperationTypeEnum.USO) {
o mesmo do de cima

2023-01-30 19:50 UTC, PinheiroLG approved these changes

2023-01-31 18:27 UTC, lucasA27 approved these changes

2023-01-31 18:27 UTC, merged